# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13d5684007b19b5343456f4cf8c30183f610b5636a5823f13350e7788c5f3575d317c31ce4e5dc22dc2203961bc8bf14dc1fc347094bc07a8aa68b827964a072

test:
  secret_key_base: ae4ba98a01c27cf0c984ca8b4062177c44db8c67aa3cebdfc1525e4a6e659449cd844e2d2a7b0ecc6c330c304a03ecde778d5bddee9c0850683bc74e0b8f8505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
